version: "3.8"

services:
  app:
    container_name: py_corrector_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    restart: always
